### ISSUE TITLE
Segmentation from page

### ISSUE THREAD

**Issue by Arideno** [githubharald/WordDetector#1]
Hello. Thank you for the repository. I have just one question. How can I segment words from a big page, not from one line. Thanks.

**Comment by githubharald** [comment]
Hi! In the linked paper (see first lines of README) you can also find an approach to segment a page into lines.

**Comment by githubharald** [comment]
added command line option --img_height, so that the image resizing can be controlled. The algo is not scale-invariant, the default parameters need a text height of roughly 25-50px. 
See README for a demo using a page image as input.
