### ISSUE TITLE
Printing detected words

### ISSUE THREAD

**Issue by Emmybritt** [githubharald/WordDetector#10]
After setting up the project, i realised that it does not print the detected words, it only show them on an image

**Comment by githubharald** [comment]
this repo is a word DETECTOR so it only detects the positions.
If you also want to read the words you have to use this repo: https://github.com/githubharald/HTRPipeline

**Comment by Emmybritt** [comment]
ok thanks i appreciate, can i connect with you on linkedin, i am building my skills in c++ and python, i will need your support in learning and building my career
