### ISSUE TITLE
sort_multiline could be improved

### ISSUE THREAD

**Issue by atsju** [githubharald/WordDetector#6]
![image](https://user-images.githubusercontent.com/4628382/147947993-9194f945-164a-4b88-9c3d-596206d7ea1a.png)

I think that people handwriting will drift randomly but the end of previous word will be about same height as next word. Also words cannot overlap too much in X.
Thus the line splitter should compare Y position of words that are near each other in X. The end of previous line not beeing necessarly compared with begining of previous one.

**Comment by atsju** [comment]
Here I have a good horizontal line but useda very small max_dist of 0.3 : 
`lines = sort_multiline(detections, max_dist=0.3, min_words_per_line=1)`

![image](https://user-images.githubusercontent.com/4628382/147950682-92575650-9a11-4414-b53f-583912263110.png)

For me line 6 and 11 could be easily computed correctly. Maybe the distance algoryhtm need to be modified in depth.

**Comment by githubharald** [comment]
can you upload the 2nd image, so I can give it a try.
for the 1st one: the y-drift is not supported.

**Comment by atsju** [comment]
Here is the file
![image](https://user-images.githubusercontent.com/4628382/148084546-ee73547f-77ff-4d59-bbe5-fdfd26ae4138.png)

I was thinking about this tonight and why wouldn't we track distance between middle of right edge and middle of left edge to do a "line" ? This might help with slight y-drift also. Well I'm just thinking out loud. If I find something interesting I might propose a PR.

**Comment by githubharald** [comment]
running the main.py script from the examples folder (`python main.py --data path/to/img --img_height 300 --theta 5`) on the image I get this output:

![Figure_1](https://user-images.githubusercontent.com/15148095/148089732-684b3f8f-6d8f-43ba-8b7b-38c85cb13ba2.png)

**Comment by atsju** [comment]
I can confirm this what you see. As I said, 

> Here I have a good horizontal line but used a very small max_dist of 0.3 :
> lines = sort_multiline(detections, max_dist=0.3, min_words_per_line=1)

OK I should not have used such a small value but the result still makes me think the line splitter could be improved.

**Comment by githubharald** [comment]
> OK I should not have used such a small value but the result still makes me think the line splitter could be improved.

The result is correct, it clusters the words into 4 lines.

**Comment by atsju** [comment]
have you tried with with max_dist = 0.3 ?
![image](https://user-images.githubusercontent.com/4628382/148094489-0a60d648-0e70-4cfb-ba46-ae4aea5abe4e.png)

**Comment by atsju** [comment]
I studied a bit the function `_cluster_lines`. The "problem" with this method is that tall words like aaaaa  will not match well with fffff even if on same line. If the lines are correctly spaced this is the case. But when the line is sligtly drifting or near the next one it might get complex. However the code is clean and I do not have a better proposal for now.

**Comment by githubharald** [comment]
The Jaccard (=1-intersection over union) distance is used, I would not go that low because this means that 100%-30%=70% intersection over union is needed so that two words are considered as neighbors. But the required 70% overlap is already quite a lot when you think about small and large words (like "in" (small) and "Lothringen" (large)).

**Comment by githubharald** [comment]
You could try some other distance functions. Jaccard distance is a proper metric, but I'm not sure if this is even needed for DBSCAN clustering (check the paper for this please). You might also use information about the x-distance between words (currently only y is used).

**Comment by githubharald** [comment]
You could also try something like this: for two words i, j, compute the minimum distance between the endpoints on the center line of the bbox (see drawing below), there are 4 possible lines, take the length of the shortest.

![grafik](https://user-images.githubusercontent.com/15148095/148096317-c5abd132-d05b-4642-9fd9-41fa22c87a9f.png)

So all the "magic" happens in selecting the right distance function, and there might be ways to also support drifting lines.

**Comment by atsju** [comment]
> You could try some other distance functions. Jaccard distance is a proper metric, but I'm not sure if this is even needed for DBSCAN clustering (check the paper for this please). You might also use information about the x-distance between words (currently only y is used).

I will let you know if I find something interesting 👍 The distance needs to be normalised for DBSCAN so I suppose the Jacquard distance choice you made is not bad. 

Your proposal is exactly what I an thinking about right now. But we need to find a way to normalize this to feed it to DBSCAN. Let the night help us.

**Comment by atsju** [comment]
thinking out loud:

Looking on first picture (drifting line)
Or we try to take X into account to avoid 7/26 beeing matched with 7/0 and thus connecting the "7" labelled lines. Again we need a way to normalize at the end

**Comment by atsju** [comment]
Hi,
The distance you proposed work quite well

``` python
def my_cluster_lines(detections: List[DetectorRes],
                   max_dist: float = 0.7,
                   min_words_per_line: int = 2) -> List[List[DetectorRes]]:
    # compute matrix containing Jaccard distances (which is a proper metric)
    num_bboxes = len(detections)
    dist_mat = np.ones((num_bboxes, num_bboxes))
    for i in range(num_bboxes):
        for j in range(i, num_bboxes):
            a = detections[i].bbox
            b = detections[j].bbox
            if a.y > b.y + b.h or b.y > a.y + a.h: # no vertical overlap
                dist_mat[i, j] = 9999999 # arbitrary large number
                continue
            dist_y = abs(a.y+a.h/2 - (b.y+b.h/2)) 
            dist_x = min(abs(a.x - b.x), abs(a.x+a.w - b.x), abs(a.x+a.w - b.x-b.w), abs(a.x - b.x-b.w)) 
            # give more impact on Y to split narrow lines
            dist_mat[i, j] = dist_mat[j, i] = dist_x + 2*dist_y

    dbscan = DBSCAN(eps=max_dist, min_samples=min_words_per_line, metric='precomputed').fit(dist_mat)

    clustered = defaultdict(list)
    for i, cluster_id in enumerate(dbscan.labels_):
        if cluster_id == -1:
            continue
        clustered[cluster_id].append(detections[i])

    res = sorted(clustered.values(), key=lambda line: [det.bbox.y + det.bbox.h / 2 for det in line])
    return res
```

The only thing is that distance is not normalized anymore. Meaning the parameter `max_dist` must be adjusted manually to a bit more than the number of pixels between words. 

I let you decide if and how you want to integrate it. Thank you for this great repo.

**Comment by githubharald** [comment]
thanks for sharing the code, I'll have a look asap and will then decide how to integrate.
