### ISSUE TITLE
pip install error with sklearn

### ISSUE THREAD

**Issue by TaylorClark1994** [githubharald/WordDetector#9]
sklearn was causing a pip install error for me. I replaced 'sklearn' with 'scikit-learn' in setup.py to fix it.

Error is as follows:

Collecting sklearn (from word-detector==1.0.0)
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\taylor.clark\AppData\Local\Temp\pip-install-wbsdua8u\sklearn_20f10a8c07054379807f2e8ea39eed76\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
                             ^^^^^^^^
        File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by githubharald** [comment]
thanks for reporting this, I'll update it, guess they renamed the package.

**Comment by amr-elsehemy** [comment]
requirements.txt 
`matplotlib
numpy
opencv-python
path
scikit-learn
pytest`


Setup.py

`from setuptools import setup
setup(
    name='word-detector',
    version='1.0.0',
    description='Word Detector',
    author='Harald Scheidl',
    packages=['word_detector'],
    url="https://github.com/githubharald/WordDetector",
    install_requires=['numpy', 'scikit-learn', 'opencv-python'],
    python_requires='>=3.7'
)
`

**Comment by githubharald** [comment]
updated both requirements and setup.py. Thanks for reporting.
